#!/usr/bin/env node
// generated by multi-repo-ponytail-graft/v1; regenerate, do not hand-edit
//
// Convergent installer for this repository's pinned Ponytail + Graft wiring.
// Safe to re-run: every target is created, updated only when derived content
// changed, or left alone when it is foreign. Second pass must be a no-op.
//
//   node .agent-tools/ponytail-graft/bootstrap.cjs            # this repo
//   node .agent-tools/ponytail-graft/bootstrap.cjs --mode=workspace
//
// --mode=workspace is for a non-git parent holding several repos: it installs
// the sidecar and builds the federated graph, and never runs `graft init`.

'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const OWNER = 'multi-repo-ponytail-graft/v1';
const GEN_HEADER = `<!-- generated by ${OWNER}; regenerate, do not hand-edit -->`;
const SIDECAR = __dirname;
const REPO = path.resolve(SIDECAR, '..', '..');
const MODULES = path.join(SIDECAR, 'node_modules');
const HOSTS = ['agents', 'claude', 'copilot', 'cursor', 'kiro']; // sorted; graft host ids
const LAUNCHER = '.agent-tools/ponytail-graft/bin/graft.cjs';
const HOOK_LAUNCHER = '.agent-tools/ponytail-graft/bin/ponytail-hook.cjs';
const MCP_ENTRY = { command: 'node', args: [LAUNCHER, 'mcp'] };
const SKILLS_MANIFEST = path.join(SIDECAR, 'skills-manifest.json');

const args = process.argv.slice(2);
const MODE = (args.find((a) => a.startsWith('--mode=')) || '--mode=repo').slice(7);
const actions = [];
const problems = [];
function act(target, action) { actions.push({ target, action }); return action; }
function problem(msg) { problems.push(msg); }

/* ---------------------------------------------------------------- helpers */

function run(cmd, cmdArgs, opts = {}) {
  return execFileSync(cmd, cmdArgs, {
    cwd: opts.cwd || REPO, encoding: 'utf8', timeout: opts.timeout || 600000,
    stdio: opts.stdio || ['ignore', 'pipe', 'pipe'],
    env: { ...process.env, DO_NOT_TRACK: '1', npm_config_fund: 'false', npm_config_audit: 'false' },
  });
}
const rel = (p) => path.relative(REPO, p) || '.';

// Three outcomes an installer must treat differently; collapsing missing with
// unparseable would let a create clobber a hand-edited broken config.
function readJsonObject(p) {
  if (!fs.existsSync(p)) return { root: {}, existed: false };
  let root;
  try { root = JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return 'unparseable'; }
  if (typeof root !== 'object' || root === null || Array.isArray(root)) return 'unparseable';
  return { root, existed: true };
}
function writeJson(p, root) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, `${JSON.stringify(root, null, 2)}\n`);
}
function writeOwned(p, content) {
  const existed = fs.existsSync(p);
  if (existed && fs.readFileSync(p, 'utf8') === content) return act(rel(p), 'unchanged');
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
  return act(rel(p), existed ? 'updated' : 'created');
}
const sha = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

/**
 * Upsert one fenced block. Markers count only when alone on their own line.
 * 0 pairs -> append (preserving EOL + final-newline convention); exactly 1 pair
 * -> replace just that region, or leave it byte-identical; anything else is
 * ambiguous and is never touched.
 */
function upsertFence(p, name, body) {
  const start = `<!-- ${name}:start -->`;
  const end = `<!-- ${name}:end -->`;
  const existed = fs.existsSync(p);
  const text = existed ? fs.readFileSync(p, 'utf8') : '';
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const lines = text.split(/\r?\n/);
  const starts = [], ends = [];
  lines.forEach((l, i) => { const t = l.trim(); if (t === start) starts.push(i); if (t === end) ends.push(i); });
  const block = [start, ...body.split('\n'), end].join(eol);

  if (starts.length === 0 && ends.length === 0) {
    if (!existed) { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, block + eol); return act(rel(p), 'created'); }
    const sep = text === '' ? '' : text.endsWith(eol + eol) ? '' : text.endsWith(eol) ? eol : eol + eol;
    fs.writeFileSync(p, text + sep + block + eol);
    return act(`${rel(p)} [${name}]`, 'appended');
  }
  if (starts.length === 1 && ends.length === 1 && ends[0] > starts[0]) {
    if (lines.slice(starts[0], ends[0] + 1).join(eol) === block) return act(`${rel(p)} [${name}]`, 'unchanged');
    fs.writeFileSync(p, [...lines.slice(0, starts[0]), ...block.split(eol), ...lines.slice(ends[0] + 1)].join(eol));
    return act(`${rel(p)} [${name}]`, 'updated');
  }
  problem(`${rel(p)}: ambiguous ${name} fence (${starts.length} start / ${ends.length} end markers); left untouched`);
  return act(`${rel(p)} [${name}]`, 'skipped-foreign');
}

// Strictly the sidecar's own copy. Not require.resolve: it walks up into parent
// node_modules, and a package whose `exports` omits ./package.json (ponytail)
// cannot be resolved that way at all.
function localPkgDir(name) {
  const dir = path.join(MODULES, ...name.split('/'));
  if (!fs.existsSync(path.join(dir, 'package.json'))) throw new Error(`${name} is not installed in the sidecar (${dir})`);
  return dir;
}

/* -------------------------------------------------- 1. dependencies + pins */

const manifest = JSON.parse(fs.readFileSync(path.join(SIDECAR, 'package.json'), 'utf8'));
const pins = manifest.dependencies;
const hasLock = fs.existsSync(path.join(SIDECAR, 'package-lock.json'));
if (!fs.existsSync(MODULES) || !hasLock) {
  run('npm', hasLock ? ['ci'] : ['install', '--no-audit', '--no-fund'], { cwd: SIDECAR });
  act('.agent-tools/ponytail-graft/node_modules', 'installed');
} else {
  act('.agent-tools/ponytail-graft/node_modules', 'present');
}

const graftDir = localPkgDir('@nanonets/graft');
const ptDir = localPkgDir('@dietrichgebert/ponytail');
const graftVer = JSON.parse(fs.readFileSync(path.join(graftDir, 'package.json'), 'utf8')).version;
const ptVer = JSON.parse(fs.readFileSync(path.join(ptDir, 'package.json'), 'utf8')).version;
if (graftVer !== pins['@nanonets/graft'] || ptVer !== pins['@dietrichgebert/ponytail']) {
  throw new Error(`installed versions (graft ${graftVer}, ponytail ${ptVer}) do not match the pins in package.json`);
}
if (hasLock) {
  const lock = JSON.parse(fs.readFileSync(path.join(SIDECAR, 'package-lock.json'), 'utf8'));
  for (const [name, want] of Object.entries(pins)) {
    const got = lock.packages && lock.packages[`node_modules/${name}`] && lock.packages[`node_modules/${name}`].version;
    if (got !== want) throw new Error(`package-lock.json has ${name}@${got}, package.json pins ${want}`);
  }
}

if (MODE === 'workspace') {
  // Command-only: never `graft init` here. A parent-level init would recursively
  // rewrite every child using the parent's runtime, clobbering the child-local
  // launchers and making the result oscillate on each pass.
  run(process.execPath, [path.join(SIDECAR, 'bin', 'graft.cjs'), 'build', '.'], { stdio: ['ignore', 'inherit', 'inherit'] });
  act('graft/workspace.json', 'built');

  const discovered = fs.readdirSync(REPO, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(REPO, d.name, '.git')))
    .map((d) => d.name).sort();
  let federated = [];
  try {
    const ws = JSON.parse(fs.readFileSync(path.join(REPO, 'graft', 'workspace.json'), 'utf8'));
    const repos = ws.repos || ws.workspaces || ws.children || [];
    federated = repos.map((r) => String(typeof r === 'string' ? r : r.name || r.path || r.root)
      .replace(/[\\/]+$/, '').split(/[\\/]/).pop()).sort();
  } catch (e) {
    problem(`could not read graft/workspace.json: ${e.message}`);
  }
  if (federated.length && JSON.stringify(federated) !== JSON.stringify(discovered)) {
    problem(`workspace child mismatch — federated [${federated}] vs discovered [${discovered}]`);
  } else if (federated.length) {
    act('workspace children', `${federated.length} federated, matches discovery`);
  }
  report();
  process.exit(problems.length ? 1 : 0);
}

/* ------------------------------------------------ 2. pre-validate foreign JSON */

for (const p of ['.claude/settings.json', '.mcp.json', '.cursor/mcp.json', '.cursor/hooks.json', '.kiro/settings/mcp.json']) {
  const full = path.join(REPO, p);
  if (readJsonObject(full) === 'unparseable') {
    throw new Error(`${p} exists but is not a JSON object; refusing to let any writer replace it. Fix or move it, then re-run.`);
  }
}

/* ----------------------------------------------------------- 3. graft init */

// graft init rewrites its whole launch surface on every pass (absolute baked
// path, bare `graft` MCP command). Snapshot it first so the restoration below
// can report NET change and a converged run reads as unchanged, not as churn.
const RESTORE_TARGETS = ['.claude/helpers/graft-statusline.cjs', '.claude/helpers/graft-hooks.cjs',
  '.cursor/hooks/graft-hooks.cjs', '.cursor/hooks.json', '.mcp.json', '.cursor/mcp.json', '.kiro/settings/mcp.json',
  '.claude/settings.json'];
const preInit = new Map(RESTORE_TARGETS.map((t) => {
  const f = path.join(REPO, t);
  return [t, fs.existsSync(f) ? sha(fs.readFileSync(f)) : null];
}));

// No --no-statusline: graft already leaves a foreign statusLine in place and
// warns. Passing the flag conditionally would delete graft's own statusline on
// the next pass, so the flag set stays identical on every run.
run(process.execPath, [path.join(SIDECAR, 'bin', 'graft.cjs'), 'init', '.', '--agents', ...HOSTS, '--no-global'],
  { stdio: ['ignore', 'inherit', 'inherit'] });
act('graft init', `ran (--agents ${HOSTS.join(' ')} --no-global)`);

/* ------------------------------- 4. restore repo-local Graft launch surface */

// Graft bakes an absolute dist/claude path into its shims and falls back to
// `npm root -g`; both resolve outside this repo. Replace the launch surface
// only — graft keeps ownership of its instruction bodies and skill file.
function localShim(entryFile, call) {
  return `#!/usr/bin/env node
// generated by ${OWNER}; regenerate, do not hand-edit
// Resolves @nanonets/graft ONLY from this repository's locked sidecar.
const path = require('path');
const fs = require('fs');
const { pathToFileURL } = require('url');

const sidecar = path.resolve(__dirname, '..', '..', '.agent-tools', 'ponytail-graft');
const modules = path.join(sidecar, 'node_modules');
let entry = null;
try {
  const dir = path.dirname(require.resolve('@nanonets/graft/package.json', { paths: [sidecar] }));
  if (dir.startsWith(modules + path.sep)) {
    const candidate = path.join(dir, 'dist', 'claude', ${JSON.stringify(entryFile)});
    if (fs.existsSync(candidate)) entry = candidate;
  }
} catch (e) { /* sidecar not installed - no-op, exactly like graft's own shim */ }

if (entry) import(pathToFileURL(entry).href).then((m) => ${call}).catch(() => {});
`;
}
const shims = [
  ['.claude/helpers/graft-statusline.cjs', localShim('statusline.js', 'm.main()')],
  ['.claude/helpers/graft-hooks.cjs', localShim('hooks.js', 'm.main(process.argv[2])')],
  ['.cursor/hooks/graft-hooks.cjs', localShim('hooks.js', 'm.main(process.argv[2])')],
];
for (const [p, content] of shims) {
  const full = path.join(REPO, p);
  if (!fs.existsSync(full)) { act(p, 'absent'); continue; }
  writeOwned(full, content);
  fs.chmodSync(full, 0o755);
}

// Cursor project hooks: graft writes an absolute shim path into each command.
{
  const p = path.join(REPO, '.cursor', 'hooks.json');
  const loaded = readJsonObject(p);
  if (loaded !== 'unparseable' && loaded.existed) {
    const before = JSON.stringify(loaded.root);
    const hooks = loaded.root.hooks;
    if (hooks && typeof hooks === 'object' && !Array.isArray(hooks)) {
      for (const list of Object.values(hooks)) {
        if (!Array.isArray(list)) continue;
        for (const e of list) {
          if (!e || typeof e.command !== 'string' || !e.command.includes('graft-hooks.cjs')) continue;
          e.command = e.command.replace(/node\s+"[^"]*graft-hooks\.cjs"/, 'node ".cursor/hooks/graft-hooks.cjs"');
        }
      }
    }
    if (JSON.stringify(loaded.root) === before) act('.cursor/hooks.json', 'unchanged');
    else { writeJson(p, loaded.root); act('.cursor/hooks.json', 'updated (relativized graft commands)'); }
  }
}

// MCP: graft writes bare `graft` (from PATH) or `npx -y`. Rewrite only its key.
for (const p of ['.mcp.json', '.cursor/mcp.json', '.kiro/settings/mcp.json']) {
  const full = path.join(REPO, p);
  const loaded = readJsonObject(full);
  if (loaded === 'unparseable' || !loaded.existed) { act(p, loaded === 'unparseable' ? 'skipped-foreign' : 'absent'); continue; }
  const servers = loaded.root.mcpServers;
  if (!servers || typeof servers !== 'object' || Array.isArray(servers) || servers.graft === undefined) { act(p, 'no graft entry'); continue; }
  if (JSON.stringify(servers.graft) === JSON.stringify(MCP_ENTRY)) { act(p, 'unchanged'); continue; }
  servers.graft = MCP_ENTRY;
  writeJson(full, loaded.root);
  act(p, 'updated (mcpServers.graft -> local launcher)');
}

for (const t of RESTORE_TARGETS.filter((x) => x !== '.claude/settings.json')) {
  const rec = actions.find((a) => a.target === t);
  if (!rec) continue;
  const f = path.join(REPO, t);
  const now = fs.existsSync(f) ? sha(fs.readFileSync(f)) : null;
  const was = preInit.get(t);
  if (now === was) rec.action = was === null ? 'absent' : 'unchanged';
  else if (was === null) rec.action = rec.action.startsWith('updated') ? 'created' : rec.action;
}

/* --------------------------------------------- 5. Ponytail instruction tier */

// Canonical body = the locked package's AGENTS.md minus its ponytail-repo
// self-reference, plus the fixed precedence note. Identical bytes everywhere.
const COMPOSITION_NOTE = `> **Ponytail + Graft precedence.** Ponytail governs how much code to write,
> never whether to keep a safeguard. Repository-specific instructions win over
> Ponytail defaults. No Ponytail rule authorizes weakening security,
> trust-boundary validation, error handling that prevents data loss,
> accessibility, or anything explicitly requested. Before writing new code,
> answer ladder rung 2 by querying this repository's locked Graft launcher.`;

const BRIDGE_BODY = `## Repository-local agent tools

This repository pins Ponytail and Graft under
\`.agent-tools/ponytail-graft/\`. Run every Graft command as
\`node .agent-tools/ponytail-graft/bin/graft.cjs ...\`; any bare \`graft ...\`
example in generated Graft guidance is shorthand for that repository-local
launcher. Never substitute a global \`graft\` or an unpinned \`npx\` invocation.
Ponytail governs implementation economy; Graft supplies repository evidence,
especially for Ponytail ladder rung 2 (reuse what already exists).`;

const rawPonytail = fs.readFileSync(path.join(ptDir, 'AGENTS.md'), 'utf8');
const PONYTAIL_BODY = rawPonytail
  .replace(/\n\(Yes, this file also applies to agents working on the ponytail repo itself\.[^)]*\)\s*$/, '\n')
  .replace(/\s+$/, '');
if (PONYTAIL_BODY.includes('ponytail repo itself')) problem('ponytail self-reference not stripped; upstream wording changed');
const PONYTAIL_FENCE_BODY = `${PONYTAIL_BODY}\n\n${COMPOSITION_NOTE}`;

for (const f of ['AGENTS.md', 'CLAUDE.md', '.github/copilot-instructions.md']) {
  upsertFence(path.join(REPO, f), 'ponytail', PONYTAIL_FENCE_BODY);
  upsertFence(path.join(REPO, f), 'ponytail-graft-local', BRIDGE_BODY);
}

// Whole-file adapters. Graft owns graft.mdc / graft.md wholesale, so Ponytail
// and the launcher bridge each get their own file beside them.
const ownedRules = [
  ['.cursor/rules/ponytail.mdc', `---\nalwaysApply: true\n---\n\n${PONYTAIL_FENCE_BODY}\n`],
  ['.cursor/rules/ponytail-graft-local.mdc', `---\nalwaysApply: true\n---\n\n${BRIDGE_BODY}\n`],
  ['.kiro/steering/ponytail.md', `---\ninclusion: always\n---\n\n${PONYTAIL_FENCE_BODY}\n`],
  ['.kiro/steering/ponytail-graft-local.md', `---\ninclusion: always\n---\n\n${BRIDGE_BODY}\n`],
];
const priorManifest = fs.existsSync(SKILLS_MANIFEST) ? JSON.parse(fs.readFileSync(SKILLS_MANIFEST, 'utf8')) : { rules: {}, skills: {} };
priorManifest.rules = priorManifest.rules || {};
priorManifest.skills = priorManifest.skills || {};
const nextManifest = { rules: {}, skills: {} };

for (const [p, content] of ownedRules) {
  const full = path.join(REPO, p);
  // A same-named file we did not write is foreign: never overwrite it.
  if (fs.existsSync(full) && priorManifest.rules[p] === undefined && sha(fs.readFileSync(full)) !== sha(Buffer.from(content))) {
    problem(`${p}: foreign file with a managed name; left untouched`);
    act(p, 'skipped-foreign');
    continue;
  }
  writeOwned(full, content);
  nextManifest.rules[p] = sha(Buffer.from(content));
}

/* ------------------------------------------------------- 6. Ponytail skills */

function listFiles(dir, base = dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) => {
    const full = path.join(dir, d.name);
    return d.isDirectory() ? listFiles(full, base) : [path.relative(base, full)];
  });
}
const skillNames = fs.readdirSync(path.join(ptDir, 'skills'), { withFileTypes: true })
  .filter((d) => d.isDirectory() && fs.existsSync(path.join(ptDir, 'skills', d.name, 'SKILL.md')))
  .map((d) => d.name).sort();

for (const host of ['.claude/skills', '.agents/skills']) {
  for (const name of skillNames) {
    const src = path.join(ptDir, 'skills', name);
    const destRel = `${host}/${name}`;
    const dest = path.join(REPO, destRel);
    const want = {};
    for (const f of listFiles(src).sort()) want[f] = sha(fs.readFileSync(path.join(src, f)));

    if (fs.existsSync(dest) && priorManifest.skills[destRel] === undefined) {
      const same = Object.entries(want).every(([f, h]) => {
        const fp = path.join(dest, f);
        return fs.existsSync(fp) && sha(fs.readFileSync(fp)) === h;
      });
      if (!same) { problem(`${destRel}: foreign skill with a managed name; left untouched`); act(destRel, 'skipped-foreign'); continue; }
    }
    let changed = false;
    for (const [f, h] of Object.entries(want)) {
      const fp = path.join(dest, f);
      if (fs.existsSync(fp) && sha(fs.readFileSync(fp)) === h) continue;
      fs.mkdirSync(path.dirname(fp), { recursive: true });
      fs.copyFileSync(path.join(src, f), fp);
      changed = true;
    }
    // Drop files a previous pin shipped and this one does not.
    for (const f of Object.keys(priorManifest.skills[destRel] || {})) {
      if (want[f] === undefined && fs.existsSync(path.join(dest, f))) { fs.unlinkSync(path.join(dest, f)); changed = true; }
    }
    nextManifest.skills[destRel] = want;
    act(destRel, changed ? 'refreshed' : 'unchanged');
  }
}
writeOwned(SKILLS_MANIFEST, `${JSON.stringify(nextManifest, null, 2)}\n`);

/* ------------------------------------------- 7. Claude Ponytail lifecycle hooks */

// Matchers and timeouts come from the locked package's own hook manifest.
const ptHooks = JSON.parse(fs.readFileSync(path.join(ptDir, 'hooks', 'claude-codex-hooks.json'), 'utf8')).hooks;
const HOOK_ACTIONS = { SessionStart: 'activate', SubagentStart: 'subagent', UserPromptSubmit: 'track' };
{
  const p = path.join(REPO, '.claude', 'settings.json');
  const loaded = readJsonObject(p);
  if (loaded === 'unparseable') throw new Error('.claude/settings.json became unparseable');
  const root = loaded.root;
  const before = JSON.stringify(root);
  root.hooks = root.hooks && typeof root.hooks === 'object' && !Array.isArray(root.hooks) ? root.hooks : {};
  for (const [event, action] of Object.entries(HOOK_ACTIONS)) {
    const upstream = (ptHooks[event] || [])[0] || {};
    const inner = (upstream.hooks || [])[0] || {};
    const entry = { type: 'command', command: `node "\${CLAUDE_PROJECT_DIR:-.}/${HOOK_LAUNCHER}" ${action}` };
    if (inner.timeout !== undefined) entry.timeout = inner.timeout;
    if (inner.statusMessage !== undefined) entry.statusMessage = inner.statusMessage;
    const block = upstream.matcher !== undefined ? { matcher: upstream.matcher, hooks: [entry] } : { hooks: [entry] };
    const prior = Array.isArray(root.hooks[event]) ? root.hooks[event] : [];
    // Identify our own by the exact launcher path, never by the word "ponytail":
    // a foreign entry mentioning ponytail must survive.
    const others = prior.filter((e) => !JSON.stringify(e ?? '').includes(HOOK_LAUNCHER));
    root.hooks[event] = [...others, block];
  }
  if (JSON.stringify(root) === before) act('.claude/settings.json [ponytail hooks]', 'unchanged');
  else { writeJson(p, root); act('.claude/settings.json [ponytail hooks]', loaded.existed ? 'updated' : 'created'); }
}

{
  const f = path.join(REPO, '.claude', 'settings.json');
  const rec = actions.find((a) => a.target === '.claude/settings.json [ponytail hooks]');
  const now = fs.existsSync(f) ? sha(fs.readFileSync(f)) : null;
  const was = preInit.get('.claude/settings.json');
  if (rec && now === was) rec.action = 'unchanged';
  else if (rec && was === null) rec.action = 'created';
}

/* --------------------------------------------------------- 8. ignore patterns */

{
  const p = path.join(REPO, '.gitignore');
  const patterns = [
    '.agent-tools/ponytail-graft/node_modules/',
    '.agent-tools/ponytail-graft/state/',
    '.claude/.ponytail-active',
    '.claude/.ponytail-statusline-nudged',
  ];
  let st = null;
  try { st = fs.lstatSync(p); } catch { /* absent */ }
  if (st && st.isSymbolicLink()) {
    problem(`.gitignore is a symlink; add these manually: ${patterns.join(' ')}`);
    act('.gitignore', 'skipped-foreign');
  } else {
    const text = st ? fs.readFileSync(p, 'utf8') : '';
    const eol = text.includes('\r\n') ? '\r\n' : '\n';
    const have = new Set(text.split(/\r?\n/).map((l) => l.trim()));
    const missing = patterns.filter((x) => !have.has(x));
    if (missing.length === 0) act('.gitignore', 'unchanged');
    else {
      const header = '# repo-local agent tooling (ponytail + graft)';
      const add = (have.has(header) ? [] : [header]).concat(missing);
      const sep = text === '' ? '' : text.endsWith(eol + eol) ? '' : text.endsWith(eol) ? eol : eol + eol;
      fs.writeFileSync(p, text + sep + add.join(eol) + eol);
      act('.gitignore', st ? 'updated' : 'created');
    }
  }
}

/* ------------------------------------------------------------- 9. documentation */

const DOC_BODY = `${GEN_HEADER}

# Repository-local agent tooling

Ponytail and Graft are pinned **inside this repository**, not installed globally.
Every launch resolves \`.agent-tools/ponytail-graft/node_modules\`, so two repos can
pin different versions and neither depends on a machine-wide install.

| Package | Pinned version |
|---|---|
| \`@nanonets/graft\` | ${pins['@nanonets/graft']} |
| \`@dietrichgebert/ponytail\` | ${pins['@dietrichgebert/ponytail']} |

Integrity comes from \`.agent-tools/ponytail-graft/package-lock.json\`; \`npm ci\`
installs exactly those bytes.

## Bootstrap (required in every clone, on every machine)

\`\`\`bash
node .agent-tools/ponytail-graft/bootstrap.cjs
\`\`\`

Tracked wiring alone is not enough: \`node_modules/\` and the Graft graph are
ignored, and Graft's generated hook shims must be re-localized after each
\`graft init\`. Run bootstrap **before** opening an agent session in a fresh clone.
It is convergent — a second run changes nothing.

## Canonical Graft invocation

\`\`\`bash
node .agent-tools/ponytail-graft/bin/graft.cjs <graft-arguments>
\`\`\`

Any bare \`graft ...\` in generated Graft guidance means this launcher. A global
\`graft\` or \`npx -y @nanonets/graft\` would run a different version.

## Updating

Edit the exact versions in \`.agent-tools/ponytail-graft/package.json\`, then:

\`\`\`bash
npm install --prefix .agent-tools/ponytail-graft
node .agent-tools/ponytail-graft/bootstrap.cjs
\`\`\`

Bootstrap refuses to continue if the installed versions, \`package.json\` and
\`package-lock.json\` disagree.

## Uninstall

Remove \`.agent-tools/ponytail-graft/\`, the \`ponytail:*\` and
\`ponytail-graft-local:*\` fences from \`AGENTS.md\`, \`CLAUDE.md\` and
\`.github/copilot-instructions.md\`, the \`ponytail*\` files under
\`.cursor/rules/\` and \`.kiro/steering/\`, the \`ponytail*\` skill directories under
\`.claude/skills/\` and \`.agents/skills/\`, and the \`ponytail-hook.cjs\` entries from
\`.claude/settings.json\`. \`node .agent-tools/ponytail-graft/bin/graft.cjs retract\`
removes Graft's own wiring.

## Host support

| Host | Graft | Ponytail |
|---|---|---|
| Claude Code | repo skill, MCP, hooks, statusline | repo instructions, skills, lifecycle hooks |
| Codex CLI/IDE | \`AGENTS.md\` + repo-local CLI | \`AGENTS.md\` + \`.agents/skills/\` |
| Cursor | repo rule, MCP, project hooks | repo rule |
| Kiro | repo steering, MCP | repo steering |
| GitHub Copilot | repo instructions + shell-accessible local CLI | repo instructions |

**Codex limitation.** Codex's MCP and hook registries are user-scoped
(\`~/.codex/\`), which this setup never writes. Codex therefore gets the
instruction tier plus the repo-local Graft CLI — not repo-local MCP or lifecycle
hooks. Instruction tier is real support, but it is not the native Ponytail
plugin: there is no automatic mode switching (\`ultra\`, \`lite\`, \`off\`) outside
Claude Code.

## Instruction fences

\`AGENTS.md\`, \`CLAUDE.md\` and \`.github/copilot-instructions.md\` carry up to three
independent fenced regions. Edit only outside them; each is rewritten in place.

| Fence | Owner |
|---|---|
| \`<!-- graft:start --> … <!-- graft:end -->\` | Graft |
| \`<!-- ponytail:start --> … <!-- ponytail:end -->\` | this setup |
| \`<!-- ponytail-graft-local:start --> … <!-- ponytail-graft-local:end -->\` | this setup |

Graft additionally owns \`.cursor/rules/graft.mdc\`, \`.kiro/steering/graft.md\` and
\`.claude/skills/graft/SKILL.md\` wholesale — Ponytail never writes into those.

## One statusline

Claude Code allows exactly one \`statusLine\`. Graft's shows graph freshness and
token savings, so Graft keeps it and Ponytail's statusline is deliberately not
installed. A pre-existing foreign statusline is left alone by both.

## Ignored, regenerated by bootstrap

\`\`\`text
.agent-tools/ponytail-graft/node_modules/   dependencies (npm ci)
.agent-tools/ponytail-graft/state/          per-repo Ponytail mode state
graft/                                      the Graft graph (graft build)
.claude/.ponytail-active                    active Ponytail mode flag
\`\`\`
`;
{
  const docsDir = path.join(REPO, 'docs');
  const generatorOwned = ['mkdocs.yml', 'mkdocs.yaml', 'docusaurus.config.js', 'docusaurus.config.ts', '_config.yml', 'book.toml']
    .some((f) => fs.existsSync(path.join(REPO, f)));
  const docPath = path.join(docsDir, 'AGENT_TOOLING.md');
  const useDocs = fs.existsSync(docsDir) && !generatorOwned &&
    (!fs.existsSync(docPath) || fs.readFileSync(docPath, 'utf8').startsWith(GEN_HEADER));
  writeOwned(useDocs ? docPath : path.join(SIDECAR, 'README.md'), DOC_BODY);
}

/* ------------------------------------------------------------- 10. build + check */

run(process.execPath, [path.join(SIDECAR, 'bin', 'graft.cjs'), 'build', '.'], { stdio: ['ignore', 'inherit', 'inherit'] });
act('graft/', 'built');

// Structure + isolation assertions over what was just written.
for (const f of ['AGENTS.md', 'CLAUDE.md', '.github/copilot-instructions.md']) {
  const full = path.join(REPO, f);
  if (!fs.existsSync(full)) { problem(`${f}: expected to exist after init`); continue; }
  const text = fs.readFileSync(full, 'utf8');
  for (const name of ['ponytail', 'ponytail-graft-local']) {
    const s = (text.match(new RegExp(`^<!-- ${name}:start -->$`, 'gm')) || []).length;
    const e = (text.match(new RegExp(`^<!-- ${name}:end -->$`, 'gm')) || []).length;
    if (s !== 1 || e !== 1) problem(`${f}: expected exactly one ${name} fence pair, found ${s}/${e}`);
  }
  const body = text.split(`<!-- ponytail:start -->`)[1];
  if (body && body.split(`<!-- ponytail:end -->`)[0].trim() !== PONYTAIL_FENCE_BODY.trim()) {
    problem(`${f}: ponytail fence body differs from the locked canonical source`);
  }
}
for (const p of ['.mcp.json', '.cursor/mcp.json', '.kiro/settings/mcp.json']) {
  const loaded = readJsonObject(path.join(REPO, p));
  if (loaded === 'unparseable' || !loaded.existed) continue;
  const g = (loaded.root.mcpServers || {}).graft;
  if (g !== undefined && JSON.stringify(g) !== JSON.stringify(MCP_ENTRY)) problem(`${p}: mcpServers.graft is not the repo-local launcher`);
}
{
  const loaded = readJsonObject(path.join(REPO, '.cursor', 'hooks.json'));
  if (loaded !== 'unparseable' && loaded.existed) {
    for (const list of Object.values(loaded.root.hooks || {})) {
      for (const e of Array.isArray(list) ? list : []) {
        if (e && typeof e.command === 'string' && e.command.includes('graft-hooks.cjs') && !e.command.includes('".cursor/hooks/graft-hooks.cjs"')) {
          problem(`.cursor/hooks.json: graft command is not repo-relative: ${e.command}`);
        }
      }
    }
  }
}
// No generated tracked file may carry an absolute checkout or home path.
const home = require('os').homedir();
for (const p of ['.claude/helpers/graft-hooks.cjs', '.claude/helpers/graft-statusline.cjs', '.cursor/hooks/graft-hooks.cjs',
  '.mcp.json', '.cursor/mcp.json', '.cursor/hooks.json', '.kiro/settings/mcp.json', '.claude/settings.json',
  '.agent-tools/ponytail-graft/bin/graft.cjs', '.agent-tools/ponytail-graft/bin/ponytail-hook.cjs']) {
  const full = path.join(REPO, p);
  if (!fs.existsSync(full)) continue;
  const text = fs.readFileSync(full, 'utf8');
  if (text.includes(home) || text.includes(REPO)) problem(`${p}: contains an absolute machine path`);
}
{
  const events = readJsonObject(path.join(REPO, '.claude', 'settings.json'));
  if (events !== 'unparseable') {
    for (const [event, list] of Object.entries(events.root.hooks || {})) {
      const n = (Array.isArray(list) ? list : []).filter((e) => JSON.stringify(e ?? '').includes(HOOK_LAUNCHER)).length;
      if (HOOK_ACTIONS[event] && n !== 1) problem(`.claude/settings.json: ${event} has ${n} ponytail entries, expected 1`);
      if (!HOOK_ACTIONS[event] && n !== 0) problem(`.claude/settings.json: ${event} unexpectedly has a ponytail entry`);
    }
  }
}

function report() {
  const w = Math.max(...actions.map((a) => a.target.length), 10);
  process.stdout.write(`\n[${OWNER}] ${rel(REPO)} — graft ${pins['@nanonets/graft']}, ponytail ${pins['@dietrichgebert/ponytail']}\n`);
  for (const a of actions) process.stdout.write(`  ${a.target.padEnd(w)}  ${a.action}\n`);
  if (problems.length) {
    process.stdout.write('\n  PROBLEMS\n');
    for (const m of problems) process.stdout.write(`  - ${m}\n`);
  }
}
report();
process.exit(problems.length ? 1 : 0);
