#!/usr/bin/env node
// generated by multi-repo-ponytail-graft/v1; regenerate, do not hand-edit
// Resolves @nanonets/graft ONLY from this repository's locked sidecar.
const path = require('path');
const fs = require('fs');
const { pathToFileURL } = require('url');

const sidecar = path.resolve(__dirname, '..', '..', '.agent-tools', 'ponytail-graft');
const modules = path.join(sidecar, 'node_modules');
let entry = null;
try {
  const dir = path.dirname(require.resolve('@nanonets/graft/package.json', { paths: [sidecar] }));
  if (dir.startsWith(modules + path.sep)) {
    const candidate = path.join(dir, 'dist', 'claude', "hooks.js");
    if (fs.existsSync(candidate)) entry = candidate;
  }
} catch (e) { /* sidecar not installed - no-op, exactly like graft's own shim */ }

if (entry) import(pathToFileURL(entry).href).then((m) => m.main(process.argv[2])).catch(() => {});
